// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/issue": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the caller using their current credentials (API key or existing JWT)\nand mints a new signed JWT that can be used as a Bearer token.\n\nThe issued token inherits the caller's **subject_id**, **tenant_id**, and **roles**,\nso it carries exactly the same authorization scope as the originating credential.\n\n**Requires** ` + "`" + `AUTH_JWT_SECRET` + "`" + ` to be configured on the server — returns 501 otherwise.\n\nTypical use-cases:\n- Upgrade from static API key to short-lived JWT\n- Refresh an expiring JWT before it expires\n- Issue scoped tokens for downstream services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Issue a JWT access token",
                "parameters": [
                    {
                        "description": "Optional — override token lifetime",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.IssueTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.IssuedTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to sign token",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "501": {
                        "description": "Token issuance not configured (AUTH_JWT_SECRET missing)",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates the credentials supplied in the request headers and returns the\ncaller's Identity (subject, tenant_id, roles). No request body required.\n\n**Simple mode** (AUTH_MODE=simple): send ` + "`" + `X-API-Key: \u003ckey\u003e` + "`" + ` header.\n**JWT mode** (AUTH_MODE=jwt): send ` + "`" + `Authorization: Bearer \u003ctoken\u003e` + "`" + ` header.\n\nUse this endpoint to verify that credentials are accepted before making\nother API calls, and to discover the tenant_id scoped to your key/token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate credentials and retrieve identity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of events across all streams, sorted by\noccurred_at DESC (newest first). Useful as an audit feed or event log.\n\nResults come from the Elasticsearch read model and are **eventually consistent**\nwith the PostgreSQL event store — recently ingested events may not appear immediately.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "List all events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page size — default 20, max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of events to skip — default 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ListEventsResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Read model query failed",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Appends a new event to the specified stream. The event is persisted in PostgreSQL\nsynchronously, then published to Kafka best-effort. A Kafka failure does NOT fail\nthis request — the event is already durable in the store. Version is assigned by\nthe store (MAX+1 per stream) and returned in the response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Ingest an event",
                "parameters": [
                    {
                        "description": "Event payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.IngestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.EventResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error (missing required fields)",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{streamID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated, version-ordered list of events for a stream from the\nElasticsearch read model. Results are **eventually consistent** with the\nPostgreSQL event store — recently ingested events may not be visible immediately.\nResponse headers communicate the data source and consistency level:\n- X-Read-Model: elasticsearch\n- X-Data-Consistency: eventual",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Query events by stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream identifier (e.g. order:1, user:42)",
                        "name": "streamID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page size — default 20, max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of events to skip — default 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.QueryResultResponse"
                        }
                    },
                    "400": {
                        "description": "stream_id missing",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Read model query failed",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns \"ok\" if the service is running. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.HealthResponse"
                        }
                    }
                }
            }
        },
        "/tenants": {
            "post": {
                "description": "Creates a logical tenant identity and returns the credentials needed to start\nmaking API calls. This is the **bootstrap endpoint** — use it once per tenant\nto obtain the first token or API key.\n\nProtected by ` + "`" + `X-Admin-Key` + "`" + ` header (configured via ` + "`" + `ADMIN_KEY` + "`" + ` env var).\nKeep this key secret and separate from regular API credentials.\n\n**JWT mode** (` + "`" + `AUTH_MODE=jwt` + "`" + `): issues a signed JWT embedding tenant_id, subject_id,\nand roles. Use the returned ` + "`" + `token` + "`" + ` as ` + "`" + `Authorization: Bearer \u003ctoken\u003e` + "`" + `.\n\n**Simple mode** (` + "`" + `AUTH_MODE=simple` + "`" + `): single-tenant only — returns the static\n` + "`" + `AUTH_API_KEY` + "`" + ` hint since all callers share the same credential.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenants"
                ],
                "summary": "Provision a new tenant and issue initial credentials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Admin secret key (ADMIN_KEY env var)",
                        "name": "X-Admin-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Tenant identity and credential options",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.CreateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.TenantCredentialsResponse"
                        }
                    },
                    "400": {
                        "description": "Missing required fields",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or missing X-Admin-Key",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to issue token",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_httpserver.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_httpserver.CreateTenantRequest": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "description": "ExpiresIn is the JWT lifetime in seconds. Defaults to 86400 (24 h). Only applies in jwt mode.",
                    "type": "integer",
                    "example": 86400
                },
                "roles": {
                    "description": "Roles assigned to the credential. Defaults to [\"writer\",\"reader\"] if omitted.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "writer",
                        "reader"
                    ]
                },
                "subject_id": {
                    "description": "SubjectID identifies the principal within the tenant (e.g. \"admin\", \"service-account\").",
                    "type": "string",
                    "example": "acme-admin"
                },
                "tenant_id": {
                    "description": "TenantID is the unique identifier for the tenant (e.g. \"acme-corp\").",
                    "type": "string",
                    "example": "acme-corp"
                }
            }
        },
        "internal_infrastructure_httpserver.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "stream_id is required"
                }
            }
        },
        "internal_infrastructure_httpserver.EventResponse": {
            "type": "object",
            "properties": {
                "correlation_id": {
                    "description": "CorrelationID is the request-scoped trace identifier from the original ingest request.\nUse it to correlate this event with the ingest log, the Postgres row, and the Elasticsearch document.",
                    "type": "string",
                    "example": "01906c2e-4a3b-7000-8000-abc123def456"
                },
                "id": {
                    "description": "ID is the globally unique event UUID.",
                    "type": "string",
                    "example": "01906c2e-4a3b-7000-8000-abc123def456"
                },
                "metadata": {
                    "description": "Metadata is the key-value metadata attached to the event.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "occurred_at": {
                    "description": "OccurredAt is the UTC timestamp when the event occurred.",
                    "type": "string",
                    "example": "2026-04-21T10:00:00Z"
                },
                "payload": {
                    "description": "Payload is the arbitrary JSON payload, returned as raw JSON.",
                    "type": "object"
                },
                "source": {
                    "description": "Source is the service that produced the event.",
                    "type": "string",
                    "example": "orders-svc"
                },
                "stream_id": {
                    "description": "StreamID is the logical stream this event belongs to.",
                    "type": "string",
                    "example": "order:1"
                },
                "tenant_id": {
                    "description": "TenantID scopes the event to a tenant; derived from the caller's Identity.",
                    "type": "string",
                    "example": "default"
                },
                "type": {
                    "description": "Type is the event type in dot-notation.",
                    "type": "string",
                    "example": "order.created"
                },
                "version": {
                    "description": "Version is monotonically increasing within the stream, assigned by the store.",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_infrastructure_httpserver.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_infrastructure_httpserver.IngestRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "description": "Metadata is optional key-value metadata for routing or tracing.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "region": "us-east-1",
                        "trace_id": "abc-123"
                    }
                },
                "payload": {
                    "description": "Payload is an arbitrary JSON value attached to the event.\nAccepted as raw JSON bytes to avoid float64 precision loss during decode.",
                    "type": "object"
                },
                "source": {
                    "description": "Source is the originating service name.",
                    "type": "string",
                    "example": "orders-svc"
                },
                "stream_id": {
                    "description": "StreamID is the target stream. Created implicitly if it does not exist.",
                    "type": "string",
                    "example": "order:1"
                },
                "type": {
                    "description": "Type is the event type in dot-notation.",
                    "type": "string",
                    "example": "order.created"
                }
            }
        },
        "internal_infrastructure_httpserver.IssueTokenRequest": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "description": "ExpiresIn is the desired token lifetime in seconds. Defaults to 3600 (1 hour). Max 86400 (24 h).",
                    "type": "integer",
                    "example": 3600
                }
            }
        },
        "internal_infrastructure_httpserver.IssuedTokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ExpiresAt is the UTC timestamp when the token expires.",
                    "type": "string",
                    "example": "2026-04-21T11:00:00Z"
                },
                "subject_id": {
                    "description": "SubjectID identifies the principal this token was issued for.",
                    "type": "string",
                    "example": "api-key"
                },
                "tenant_id": {
                    "description": "TenantID is the tenant scope embedded in the token.",
                    "type": "string",
                    "example": "default"
                },
                "token": {
                    "description": "Token is the signed JWT to use in subsequent requests as \"Authorization: Bearer \u003ctoken\u003e\".",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "internal_infrastructure_httpserver.ListEventsResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "description": "Events is the page of events sorted by occurred_at DESC.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_httpserver.EventResponse"
                    }
                },
                "limit": {
                    "description": "Limit is the page size applied to this query.",
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "description": "Offset is the number of events skipped.",
                    "type": "integer",
                    "example": 0
                },
                "read_model": {
                    "description": "ReadModel identifies the data source (\"elasticsearch\").",
                    "type": "string",
                    "example": "elasticsearch"
                },
                "total": {
                    "description": "Total is the total number of events in the index (for pagination).",
                    "type": "integer",
                    "example": 128
                }
            }
        },
        "internal_infrastructure_httpserver.QueryResultResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "description": "Events is the ordered (version ASC) page of events.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_httpserver.EventResponse"
                    }
                },
                "limit": {
                    "description": "Limit is the page size applied to this query.",
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "description": "Offset is the number of events skipped.",
                    "type": "integer",
                    "example": 0
                },
                "read_model": {
                    "description": "ReadModel identifies the data source (\"elasticsearch\").",
                    "type": "string",
                    "example": "elasticsearch"
                },
                "stream_id": {
                    "description": "StreamID is the queried stream identifier.",
                    "type": "string",
                    "example": "order:1"
                },
                "total": {
                    "description": "Total is the total number of matching events, useful for pagination.",
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "internal_infrastructure_httpserver.TenantCredentialsResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ExpiresAt is the UTC expiry of the issued token. Only present in jwt mode.",
                    "type": "string",
                    "example": "2026-04-22T21:57:00Z"
                },
                "mode": {
                    "description": "Mode reflects the active auth mode (\"jwt\" or \"simple\").",
                    "type": "string",
                    "example": "jwt"
                },
                "note": {
                    "description": "Note is a human-readable hint returned in simple mode.",
                    "type": "string",
                    "example": "simple mode is single-tenant — use X-API-Key: \u003cAUTH_API_KEY\u003e"
                },
                "subject_id": {
                    "description": "SubjectID is the principal this credential belongs to.",
                    "type": "string",
                    "example": "acme-admin"
                },
                "tenant_id": {
                    "description": "TenantID is the provisioned tenant identifier.",
                    "type": "string",
                    "example": "acme-corp"
                },
                "token": {
                    "description": "Token is the signed JWT to use as \"Authorization: Bearer \u003ctoken\u003e\". Only present in jwt mode.",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "internal_infrastructure_httpserver.TokenResponse": {
            "type": "object",
            "properties": {
                "roles": {
                    "description": "Roles lists the permissions granted to this credential.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "writer",
                        "reader"
                    ]
                },
                "subject_id": {
                    "description": "SubjectID identifies the authenticated principal.",
                    "type": "string",
                    "example": "api-key"
                },
                "tenant_id": {
                    "description": "TenantID is the tenant scope associated with this credential.",
                    "type": "string",
                    "example": "default"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Static API key. Default value for local dev: dev-api-key. Configured via AUTH_API_KEY env var.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "description": "JWT Bearer token. Format: \"Bearer {token}\". Enable with AUTH_MODE=jwt and AUTH_JWT_SECRET env var.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Event Streaming and Audit API",
	Description:      "HTTP API for ingesting and querying events in the Event Streaming & Audit Platform.\n\n## Authentication\nAll /events endpoints require authentication. /health and /swagger are public.\nSet AUTH_MODE=simple (default) to use X-API-Key, or AUTH_MODE=jwt for Bearer tokens.\n\n## Data consistency\nWrite path: PostgreSQL (source of truth) → Kafka → Elasticsearch (read model).\nGET /events/{streamID} is served from Elasticsearch and is eventually consistent.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
